'use client';

import { useEffect,useState } from 'react';
import { PublicShell,useSiteSettings } from '@/components/SiteChrome';
import { SetupNotice } from '@/components/SetupNotice';
import { FavouriteButton } from '@/components/FavouriteButton';
import { isFirebaseConfigured } from '@/lib/firebase/client';
import { listVideos,type Video } from '@/services/media';

export default function VideosPage(){const settings=useSiteSettings();const [items,setItems]=useState<Video[]>([]);const [loading,setLoading]=useState(isFirebaseConfigured);const [error,setError]=useState('');useEffect(()=>{if(!isFirebaseConfigured)return;listVideos().then(setItems).catch(reason=>setError(reason instanceof Error?reason.message:'Unable to load videos.')).finally(()=>setLoading(false));},[]);return <PublicShell><main className="video-index"><section className="video-hero"><div><p>OFFICIAL YOUTUBE CHANNEL</p><h1>Watch RJ Tractor Techs</h1><span>Tractor stories, model explainers and topics from the field. Explore the published videos or continue on the RJ Tractor Techs channel.</span><a href={settings.youtube||'https://www.youtube.com/@Rjtractortechs'} target="_blank" rel="noreferrer">Visit YouTube channel ↗</a></div></section>{!isFirebaseConfigured?<SetupNotice/>:<section className="video-list">{loading?<div className="detail-loading">Loading videos…</div>:error?<div className="error-state"><h3>Videos are unavailable.</h3><p>{error}</p></div>:!items.length?<div className="empty-state"><h3>Your next watch is on the channel.</h3><p>The website library has no published videos yet. Visit our channel to keep exploring.</p><a href={settings.youtube||'https://www.youtube.com/@Rjtractortechs'} target="_blank" rel="noreferrer">Explore YouTube ↗</a></div>:<div className="video-grid">{items.map(item=><article key={item.id}><a className="video-thumb" href={'/videos/'+item.slug} style={item.thumbnail?{backgroundImage:'url('+item.thumbnail+')'}:undefined}><span>▶</span></a><section><p>{item.category??'RJ TRACTOR TECHS'}</p><h2><a href={'/videos/'+item.slug}>{item.title}</a></h2><div>{item.tractorName&&<small>{item.tractorName}</small>}<FavouriteButton compact itemId={item.id} itemType="video" title={item.title} href={'/videos/'+item.slug} image={item.thumbnail}/></div></section></article>)}</div>}</section>}</main></PublicShell>;}

