import {initializeApp} from 'firebase-admin/app';
import {getAuth} from 'firebase-admin/auth';
import {getFirestore} from 'firebase-admin/firestore';
import {HttpsError,onCall} from 'firebase-functions/v2/https';
initializeApp();
async function callerRole(uid:string){const snap=await getFirestore().doc(`admins/${uid}`).get();return snap.exists&&snap.data()?.active?snap.data()?.role:null;}
async function requireAdmin(uid?:string){if(!uid)throw new HttpsError('unauthenticated','Sign in required.');const role=await callerRole(uid);if(!['Admin','Super Admin'].includes(role))throw new HttpsError('permission-denied','Administrator access required.');return role;}
export const setUserRole=onCall(async request=>{const caller=await requireAdmin(request.auth?.uid);const {uid,role}=request.data as {uid?:string;role?:string};if(!uid||!['Customer','Editor','Admin','Super Admin'].includes(role??''))throw new HttpsError('invalid-argument','Valid uid and role are required.');if((role==='Admin'||role==='Super Admin')&&caller!=='Super Admin')throw new HttpsError('permission-denied','Only a Super Admin can assign administrator roles.');await getAuth().setCustomUserClaims(uid,{admin:role==='Admin'||role==='Super Admin',superAdmin:role==='Super Admin',role});await getFirestore().doc(`users/${uid}`).set({role,updatedAt:new Date()},{merge:true});if(role==='Admin'||role==='Super Admin')await getFirestore().doc(`admins/${uid}`).set({role,active:true,updatedAt:new Date()},{merge:true});return {ok:true};});
export const setUserDisabled=onCall(async request=>{await requireAdmin(request.auth?.uid);const {uid,disabled}=request.data as {uid?:string;disabled?:boolean};if(!uid||typeof disabled!=='boolean')throw new HttpsError('invalid-argument','Valid uid and disabled state are required.');if(uid===request.auth?.uid&&disabled)throw new HttpsError('failed-precondition','You cannot disable your own account.');await getAuth().updateUser(uid,{disabled});await getFirestore().doc(`users/${uid}`).set({disabled,updatedAt:new Date()},{merge:true});return {ok:true};});
export const syncYouTubeVideos=onCall(async request=>{await requireAdmin(request.auth?.uid);const apiKey=process.env.YOUTUBE_API_KEY;const channelId=process.env.YOUTUBE_CHANNEL_ID;if(!apiKey||!channelId)throw new HttpsError('failed-precondition','Configure YOUTUBE_API_KEY and YOUTUBE_CHANNEL_ID.');const url=new URL('https://www.googleapis.com/youtube/v3/search');url.search=new URLSearchParams({part:'snippet',channelId,maxResults:'25',order:'date',type:'video',key:apiKey}).toString();const response=await fetch(url);if(!response.ok)throw new HttpsError('internal','YouTube Data API request failed.');const payload=await response.json()as{items?:Array<{id:{videoId:string};snippet:{title:string;description:string;publishedAt:string;thumbnails?:{high?:{url:string}}}}>};for(const item of payload.items??[]){const slug=item.snippet.title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');await getFirestore().doc(`videos/${item.id.videoId}`).set({title:item.snippet.title,slug,description:item.snippet.description,youtubeVideoId:item.id.videoId,thumbnail:item.snippet.thumbnails?.high?.url??'',publishedAt:new Date(item.snippet.publishedAt),status:'draft',source:'youtube',updatedAt:new Date()},{merge:true});}return{ok:true,synced:payload.items?.length??0};});
