'use client';
import { LocalizedElement } from '@/components/LocalizedElement';


import { useEffect,useState } from 'react';
import { PublicShell } from '@/components/SiteChrome';
import { SetupNotice } from '@/components/SetupNotice';
import { isFirebaseConfigured } from '@/lib/firebase/client';
import { getDealer,type Dealer } from '@/services/media';

export default function DealerDetailClient({slug}:{slug:string}){const [dealer,setDealer]=useState<Dealer|null>(null);const [loading,setLoading]=useState(isFirebaseConfigured);useEffect(()=>{if(!isFirebaseConfigured)return;getDealer(slug).then(setDealer).finally(()=>setLoading(false));},[slug]);return <PublicShell><main className="dealer-detail">{!isFirebaseConfigured?<SetupNotice/>:loading?<LocalizedElement as="div" className="detail-loading">Loading dealer…</LocalizedElement>:!dealer?<LocalizedElement as="div" className="empty-state"><LocalizedElement as="h3">Dealer not found.</LocalizedElement><LocalizedElement as="a" href="/dealers">Browse dealers →</LocalizedElement></LocalizedElement>:<><section className="dealer-profile"><LocalizedElement as="div" className="dealer-logo">{dealer.logo?<LocalizedElement as="img" src={dealer.logo} alt={dealer.name+' logo'}/>:dealer.name.slice(0,2).toUpperCase()}</LocalizedElement><article><LocalizedElement as="p">{dealer.verified?'✓ VERIFIED DEALER':'DEALER PROFILE'}</LocalizedElement><LocalizedElement as="h1">{dealer.name}</LocalizedElement><LocalizedElement as="span">{dealer.address}, {dealer.city}, {dealer.district}, {dealer.state} {dealer.pincode}</LocalizedElement><LocalizedElement as="small">{dealer.brand??'Published tractor dealer'}</LocalizedElement></article></section><section className="dealer-contact"><LocalizedElement as="div"><LocalizedElement as="h2">Contact dealer</LocalizedElement>{dealer.phone&&<LocalizedElement as="a" href={'tel:'+dealer.phone}>Call {dealer.phone}</LocalizedElement>}{dealer.whatsapp&&<LocalizedElement as="a" href={'https://wa.me/'+dealer.whatsapp.replace(/\D/g,'')} target="_blank" rel="noreferrer">WhatsApp dealer ↗</LocalizedElement>}{dealer.email&&<LocalizedElement as="a" href={'mailto:'+dealer.email}>Email dealer</LocalizedElement>}</LocalizedElement><LocalizedElement as="div"><LocalizedElement as="h2">Services</LocalizedElement>{dealer.services?.map(service=><LocalizedElement as="span" key={service}>{service}</LocalizedElement>)}</LocalizedElement><LocalizedElement as="div"><LocalizedElement as="h2">Location</LocalizedElement>{dealer.latitude&&dealer.longitude?<LocalizedElement as="a" href={'https://maps.google.com/?q='+dealer.latitude+','+dealer.longitude} target="_blank" rel="noreferrer">Open in Maps ↗</LocalizedElement>:<LocalizedElement as="span">Map coordinates not published.</LocalizedElement>}</LocalizedElement></section></>}</main></PublicShell>;}

