import{addDoc,collection,deleteDoc,doc,getDoc,getDocs,limit,orderBy,query,serverTimestamp,updateDoc,where}from'firebase/firestore';import type{QueryConstraint}from'firebase/firestore';import{db,isFirebaseConfigured,isLocalDemo}from'@/lib/firebase/client';
export type LeadStatus='New'|'Contacted'|'Interested'|'Follow-up'|'Converted'|'Closed'|'Spam';export interface Lead{id:string;name:string;phone:string;email?:string;city:string;state:string;tractorId?:string;tractorName?:string;dealerId?:string;message?:string;source:string;status:LeadStatus;assignedTo?:string;notes?:string;userId?:string;createdAt?:{toDate?:()=>Date};updatedAt?:unknown}export type NewLead=Pick<Lead,'name'|'phone'|'city'|'state'|'source'>&Partial<Pick<Lead,'email'|'tractorId'|'tractorName'|'dealerId'|'message'|'userId'>>;
function database(){if(!isFirebaseConfigured||!db)throw new Error('Firebase is not configured.');return db}function demos():Lead[]{if(typeof window==='undefined')return[];return JSON.parse(localStorage.getItem('rj-demo-leads')??'[]')as Lead[]}function save(items:Lead[]){localStorage.setItem('rj-demo-leads',JSON.stringify(items));window.dispatchEvent(new CustomEvent('rj-demo-data',{detail:{collection:'leads'}}));}
export async function createLead(input:NewLead){if(isLocalDemo&&!db){save([{...input,id:`demo-${Date.now()}`,status:'New',assignedTo:'',notes:''}as Lead,...demos()]);return}const clean=Object.fromEntries(Object.entries(input).filter(([,v])=>v!==undefined&&v!==''));return addDoc(collection(database(),'leads'),{...clean,status:'New',assignedTo:null,notes:'',createdAt:serverTimestamp(),updatedAt:serverTimestamp()})}
export async function getAdminRole(userId:string){if(isLocalDemo&&!db)return'Super Admin';const snap=await getDoc(doc(database(),'admins',userId));if(!snap.exists()||snap.data().active!==true)return null;return String(snap.data().role??'')}
export async function listLeads(filters:{status?:LeadStatus;source?:string}={}){if(isLocalDemo&&!db)return demos().filter(x=>(!filters.status||x.status===filters.status)&&(!filters.source||x.source===filters.source));const clauses:QueryConstraint[]=[orderBy('createdAt','desc'),limit(100)];if(filters.status)clauses.unshift(where('status','==',filters.status));if(filters.source)clauses.unshift(where('source','==',filters.source));const snap=await getDocs(query(collection(database(),'leads'),...clauses));return snap.docs.map(x=>({id:x.id,...x.data()})as Lead)}
export async function updateLeadStatus(id:string,status:LeadStatus,assignedTo?:string){if(isLocalDemo&&!db){save(demos().map(x=>x.id===id?{...x,status,assignedTo:assignedTo??x.assignedTo}:x));return}await updateDoc(doc(database(),'leads',id),{status,...(assignedTo!==undefined?{assignedTo}:{}),updatedAt:serverTimestamp()})}
export async function updateLeadNotes(id:string,notes:string){if(isLocalDemo&&!db){save(demos().map(x=>x.id===id?{...x,notes,updatedAt:new Date().toISOString()}:x));return}await updateDoc(doc(database(),'leads',id),{notes,updatedAt:serverTimestamp()})}
export async function deleteLead(id:string){if(isLocalDemo&&!db){save(demos().filter(x=>x.id!==id));return}await deleteDoc(doc(database(),'leads',id))}
