'use client';
import { LocalizedElement } from '@/components/LocalizedElement';


import {isLocalDemo,auth} from '@/lib/firebase/client';
import { PublicShell } from '@/components/SiteChrome';
import { SetupNotice } from '@/components/SetupNotice';
import { useAuth } from '@/hooks/useAuth';

export default function AccountPage() {
  const localPreview=isLocalDemo&&!auth;
  const { user, loading, configured, logOut } = useAuth();
  return <PublicShell><main className="account-page"><LocalizedElement as="div" className="page-hero"><LocalizedElement as="p">MY ACCOUNT</LocalizedElement><LocalizedElement as="h1">Your tractor research</LocalizedElement><LocalizedElement as="span">Return to saved models, read editorial reviews and send an enquiry.</LocalizedElement></LocalizedElement>{!configured ? <SetupNotice /> : loading ? <LocalizedElement as="div" className="detail-loading">Loading your account…</LocalizedElement> : !user ? <LocalizedElement as="div" className="empty-state"><LocalizedElement as="h3">Sign in to view your account.</LocalizedElement><LocalizedElement as="a" href="/login">Sign in →</LocalizedElement></LocalizedElement> : <section className="account-panel"><aside><LocalizedElement as="div" className="avatar">{(user.displayName ?? user.email ?? 'U')[0].toUpperCase()}</LocalizedElement><LocalizedElement as="strong">{user.displayName ?? 'RJ Tractor Techs member'}</LocalizedElement><LocalizedElement as="span">{user.email}</LocalizedElement><nav><LocalizedElement as="a" className="active" href="/account">Overview</LocalizedElement><LocalizedElement as="a" href="/account/favourites">Favourites</LocalizedElement><LocalizedElement as="a" href="/reviews">Editorial reviews</LocalizedElement><LocalizedElement as="a" href="/account/enquiries">Enquiries</LocalizedElement></nav><LocalizedElement as="button" onClick={logOut} disabled={localPreview}>{localPreview?'Local preview account':'Sign out'}</LocalizedElement></aside><LocalizedElement as="div"><LocalizedElement as="p">ACCOUNT OVERVIEW</LocalizedElement><LocalizedElement as="h2">Welcome back.</LocalizedElement><LocalizedElement as="div" className="account-cards"><LocalizedElement as="a" href="/account/favourites"><LocalizedElement as="strong">♡</LocalizedElement><LocalizedElement as="span">Saved tractors</LocalizedElement><LocalizedElement as="small">View favourites →</LocalizedElement></LocalizedElement><LocalizedElement as="a" href="/compare"><LocalizedElement as="strong">⇄</LocalizedElement><LocalizedElement as="span">Compare tractors</LocalizedElement><LocalizedElement as="small">Start comparing →</LocalizedElement></LocalizedElement><LocalizedElement as="a" href="/tractors"><LocalizedElement as="strong">⌕</LocalizedElement><LocalizedElement as="span">Continue research</LocalizedElement><LocalizedElement as="small">Browse tractors →</LocalizedElement></LocalizedElement><LocalizedElement as="a" href="/reviews"><LocalizedElement as="strong">☆</LocalizedElement><LocalizedElement as="span">Editorial reviews</LocalizedElement><LocalizedElement as="small">Read reviews →</LocalizedElement></LocalizedElement><LocalizedElement as="a" href="/account/enquiries"><LocalizedElement as="strong">↗</LocalizedElement><LocalizedElement as="span">Send an enquiry</LocalizedElement><LocalizedElement as="small">Ask a question →</LocalizedElement></LocalizedElement></LocalizedElement></LocalizedElement></section>}</main></PublicShell>;
}

