'use client';
import {PublicShell,useSiteSettings} from './SiteChrome';
import {PageIntro,ReadingContent} from './PublicPageParts';
export function AboutPage(){const settings=useSiteSettings();return <PublicShell><main className="about-page">
  <PageIntro eyebrow="ABOUT RJ TRACTOR TECHS" title="Good research. Clearer choices." description="A place to explore tractors, understand the details and bring your next purchase into focus."/>
  <section className="about-story"><div className="about-photo"><img src="/hero/mahindra-575-di-xp-plus.webp" alt="A red tractor in a farm field"/><span>FOR THE WORK AHEAD</span></div><article><p className="section-kicker">THE IDEA BEHIND THE PLATFORM</p><h2>Tractor information, brought together.</h2>{settings.about?<ReadingContent text={settings.about}/>:<><p>Choosing a tractor comes with plenty of questions. Which models should you explore? What do their specifications say? What should you ask when you visit a dealer?</p><p>RJ Tractor Techs brings model pages, comparisons, written reviews and videos into one place. Start with a question, follow the details and build a shortlist at your own pace.</p><p>Our focus is straightforward: make tractor research easier to explore and easier to understand.</p></>}<a className="text-action" href="/tractors">Explore the tractor catalog <span>→</span></a></article></section>
  <section className="about-paths"><div><p className="section-kicker">CHOOSE YOUR STARTING POINT</p><h2>One question. More ways to find an answer.</h2></div><div className="about-path-grid">{[['01','Explore the models','Browse the catalog and open a model page for its listed specifications.','/tractors'],['02','Put them side by side','Use the comparison tool to bring your shortlist into one view.','/compare'],['03','Read and watch','Find written reviews, articles and videos to continue your research.','/articles']].map(([number,title,text,href])=><a key={href} href={href}><span>{number}</span><h3>{title}</h3><p>{text}</p><b aria-hidden="true">↗</b></a>)}</div></section>
  <section className="about-principles"><div><p className="section-kicker">A NOTE ON THE DETAILS</p><h2>Use the information. Keep asking questions.</h2></div><div><p>Use published specifications and reviews to prepare for a conversation with the manufacturer or dealer. Confirm the exact model, available features and final quotation before deciding.</p><p>Spotted a detail that needs another look? Tell us which page you are reading and what you would like us to check.</p><a className="text-action" href="/contact">Send a question or correction <span>→</span></a></div></section>
  <section className="about-watch"><span aria-hidden="true">▶</span><div><p className="section-kicker">RJ TRACTOR TECHS ON YOUTUBE</p><h2>Keep the conversation going.</h2><p>Explore the channel for tractor videos and more topics from the field.</p></div><a href={settings.youtube||'https://www.youtube.com/@Rjtractortechs'} target="_blank" rel="noreferrer">Visit the channel ↗</a></section>
</main></PublicShell>;}
