'use client';
import { LocalizedElement } from '@/components/LocalizedElement';

import {PublicShell,useSiteSettings} from './SiteChrome';
import {PageIntro,ReadingContent} from './PublicPageParts';
export function AboutPage(){const settings=useSiteSettings();return <PublicShell><main className="about-page">
  <PageIntro eyebrow="ABOUT RJ TRACTOR TECHS" title="Good research. Clearer choices." description="A place to explore tractors, understand the details and bring your next purchase into focus."/>
  <section className="about-story"><LocalizedElement as="div" className="about-photo"><LocalizedElement as="img" src="/hero/mahindra-575-di-xp-plus.webp" alt="A red tractor in a farm field"/><LocalizedElement as="span">FOR THE WORK AHEAD</LocalizedElement></LocalizedElement><article><LocalizedElement as="p" className="section-kicker">THE IDEA BEHIND THE PLATFORM</LocalizedElement><LocalizedElement as="h2">Tractor information, brought together.</LocalizedElement>{settings.about?<ReadingContent text={settings.about}/>:<><LocalizedElement as="p">Choosing a tractor comes with plenty of questions. Which models should you explore? What do their specifications say? What should you ask when you visit a dealer?</LocalizedElement><LocalizedElement as="p">RJ Tractor Techs brings model pages, comparisons, written reviews and videos into one place. Start with a question, follow the details and build a shortlist at your own pace.</LocalizedElement><LocalizedElement as="p">Our focus is straightforward: make tractor research easier to explore and easier to understand.</LocalizedElement></>}<LocalizedElement as="a" className="text-action" href="/tractors">Explore the tractor catalog <LocalizedElement as="span">→</LocalizedElement></LocalizedElement></article></section>
  <section className="about-paths"><LocalizedElement as="div"><LocalizedElement as="p" className="section-kicker">CHOOSE YOUR STARTING POINT</LocalizedElement><LocalizedElement as="h2">One question. More ways to find an answer.</LocalizedElement></LocalizedElement><LocalizedElement as="div" className="about-path-grid">{[['01','Explore the models','Browse the catalog and open a model page for its listed specifications.','/tractors'],['02','Put them side by side','Use the comparison tool to bring your shortlist into one view.','/compare'],['03','Read and watch','Find written reviews, articles and videos to continue your research.','/articles']].map(([number,title,text,href])=><LocalizedElement as="a" key={href} href={href}><LocalizedElement as="span">{number}</LocalizedElement><LocalizedElement as="h3">{title}</LocalizedElement><LocalizedElement as="p">{text}</LocalizedElement><b aria-hidden="true">↗</b></LocalizedElement>)}</LocalizedElement></section>
  <section className="about-principles"><LocalizedElement as="div"><LocalizedElement as="p" className="section-kicker">A NOTE ON THE DETAILS</LocalizedElement><LocalizedElement as="h2">Use the information. Keep asking questions.</LocalizedElement></LocalizedElement><LocalizedElement as="div"><LocalizedElement as="p">Use published specifications and reviews to prepare for a conversation with the manufacturer or dealer. Confirm the exact model, available features and final quotation before deciding.</LocalizedElement><LocalizedElement as="p">Spotted a detail that needs another look? Tell us which page you are reading and what you would like us to check.</LocalizedElement><LocalizedElement as="a" className="text-action" href="/contact">Send a question or correction <LocalizedElement as="span">→</LocalizedElement></LocalizedElement></LocalizedElement></section>
  <section className="about-watch"><LocalizedElement as="span" aria-hidden="true">▶</LocalizedElement><LocalizedElement as="div"><LocalizedElement as="p" className="section-kicker">RJ TRACTOR TECHS ON YOUTUBE</LocalizedElement><LocalizedElement as="h2">Keep the conversation going.</LocalizedElement><LocalizedElement as="p">Explore the channel for tractor videos and more topics from the field.</LocalizedElement></LocalizedElement><LocalizedElement as="a" href={settings.youtube||'https://www.youtube.com/@Rjtractortechs'} target="_blank" rel="noreferrer">Visit the channel ↗</LocalizedElement></section>
</main></PublicShell>;}
