'use client';
import { LocalizedElement } from '@/components/LocalizedElement';

import type {ReactNode} from 'react';
import {parseReadingContent} from '@/utils/reading-content';
import {usePathname} from 'next/navigation';

export function PageIntro({eyebrow,title,description,children}:{eyebrow:string;title:string;description:string;children?:ReactNode}){
  return <section className="page-hero"><LocalizedElement as="p">{eyebrow}</LocalizedElement><LocalizedElement as="h1">{title}</LocalizedElement><LocalizedElement as="span">{description}</LocalizedElement>{children}</section>;
}
export function EmptyContent({title,description,href='/tractors',action='Explore tractors'}:{title:string;description:string;href?:string;action?:string}){
  return <LocalizedElement as="div" className="empty-state"><LocalizedElement as="span" className="empty-mark" aria-hidden="true">↗</LocalizedElement><LocalizedElement as="h3">{title}</LocalizedElement><LocalizedElement as="p">{description}</LocalizedElement><LocalizedElement as="a" href={href}>{action} <LocalizedElement as="span" aria-hidden="true">→</LocalizedElement></LocalizedElement></LocalizedElement>;
}
export function ReadingContent({text}:{text:string}){
  return <LocalizedElement as="div" className="reading-copy">{parseReadingContent(text).map((block,index)=>block.kind==='list'?<ul key={index}>{block.items.map((item,i)=><LocalizedElement as="li" key={i}>{item}</LocalizedElement>)}</ul>:block.kind==='heading'?(block.level===3?<LocalizedElement as="h3" key={index}>{block.text}</LocalizedElement>:<LocalizedElement as="h2" key={index}>{block.text}</LocalizedElement>):<LocalizedElement as="p" key={index}>{block.text}</LocalizedElement>)}</LocalizedElement>;
}
const destinations:Record<string,[string,string]>={tractors:['Tractors','/tractors'],tractor:['Tractors','/tractors'],brand:['Brands','/brands'],brands:['Brands','/brands'],articles:['Articles','/articles'],category:['Articles','/articles'],news:['News','/news'],videos:['Videos','/videos'],reviews:['Reviews','/reviews'],equipment:['Equipment','/equipment'],dealers:['Dealers','/dealers'],account:['My account','/account'],'emi-calculator':['EMI calculator','/emi-calculator'],'new-tractors':['New tractors','/new-tractors'],'upcoming-tractors':['Upcoming tractors','/upcoming-tractors'],'privacy-policy':['Privacy policy','/privacy-policy'],'terms-and-conditions':['Terms and conditions','/terms-and-conditions'],'cookie-policy':['Cookie policy','/cookie-policy']};
export function PublicBreadcrumbs(){
  const path=usePathname();const parts=path.split('/').filter(Boolean);if(!parts.length)return null;
  const group=destinations[parts[0]];const label=(group&&parts.length===1?group[0]:decodeURIComponent(parts.at(-1)??'').replaceAll('-',' '));
  return <nav className="public-breadcrumbs" aria-label="Breadcrumb"><LocalizedElement as="a" href="/">Home</LocalizedElement><LocalizedElement as="span" aria-hidden="true">/</LocalizedElement>{parts.length>1&&group&&<><LocalizedElement as="a" href={group[1]}>{group[0]}</LocalizedElement><LocalizedElement as="span" aria-hidden="true">/</LocalizedElement></>}<LocalizedElement as="span" aria-current="page">{label}</LocalizedElement></nav>;
}
type Guide={eyebrow:string;title:string;intro:string;items:[string,string][];link:[string,string]};
const guides:Record<string,Guide>={
  tractors:{eyebrow:'BUILD YOUR SHORTLIST',title:'Start with the work. Then compare the details.',intro:'A useful shortlist begins with your own requirements, not just a model name.',items:[['List your jobs','Write down the field work, transport and implements you want your next tractor to handle.'],['Compare the same details','Keep power, transmission, drive type and quoted price together when reviewing models.'],['Take questions to the dealer','Ask about the exact variant, a demonstration, available service and what is included in the quotation.']],link:['Compare your shortlist','/compare']},
  brands:{eyebrow:'LOOK BEYOND THE LOGO',title:'Get to know the range.',intro:'Move from the manufacturer to the individual model, then compare the information that matters to you.',items:[['Explore a brand','Open a manufacturer profile to see the models currently listed in our catalog.'],['Check the model','Read the specific model page instead of assuming every tractor in the range has the same equipment.'],['Keep your options open','Put models from different manufacturers beside each other before narrowing your shortlist.']],link:['Browse the tractor catalog','/tractors']},
  articles:{eyebrow:'A LITTLE CONTEXT GOES A LONG WAY',title:'Read. Research. Put it into practice.',intro:'Use the reading room to support the next step in your tractor research.',items:[['Buying questions','Make a note of the questions you want answered before visiting a dealership.'],['Model research','Follow a guide with a look at the specifications of the tractors on your shortlist.'],['Visual explainers','Switch to the video library when you want to see a topic explained on screen.']],link:['Explore the video library','/videos']},
  reviews:{eyebrow:'READ WITH A PURPOSE',title:'A review is one part of the decision.',intro:'Bring your own priorities to each review and use it alongside the model specifications.',items:[['Your priorities','Focus on the controls, features and working conditions relevant to the jobs you have in mind.'],['The whole picture','Read the verdict with the full review, rather than relying on a score alone.'],['Your next step','Compare models and take any unanswered questions into a dealer conversation.']],link:['Compare tractor specifications','/compare']},
  equipment:{eyebrow:'PLAN THE COMPLETE SETUP',title:'The right questions for your next implement.',intro:'Keep the tractor and the equipment in the same conversation.',items:[['Start with the task','Describe the job, the field conditions and how often you expect to use the equipment.'],['Check compatibility','Ask the equipment supplier to confirm compatibility with your exact tractor and its published specifications.'],['Ask what is included','Request the supplied accessories, setup requirements and service details in the equipment quotation.']],link:['Research your tractor','/tractors']},
  dealers:{eyebrow:'BEFORE YOUR VISIT',title:'Make the conversation count.',intro:'Arrive with a shortlist and a few clear questions.',items:[['Confirm availability','Contact the dealership about the exact model and variant before travelling.'],['Request a written quote','Ask for an itemised quotation and a clear explanation of what it includes.'],['Discuss support','Ask who to contact for service, spare parts and questions after delivery.']],link:['Build a tractor shortlist','/tractors']},
  compare:{eyebrow:'FROM SPECS TO A SHORTLIST',title:'Compare what matters to your work.',intro:'Use the table as a starting point for a more informed conversation.',items:[['Choose your models','Select two or three tractors from the published catalog.'],['Review each row','Look at the specifications together and note where information still needs confirmation.'],['Keep researching','Open a model page for more details or take your shortlist to a dealer.']],link:['Find a dealer','/dealers']},
  videos:{eyebrow:'KEEP EXPLORING',title:'From the video to the details.',intro:'Continue your research with a model page, a written review or a comparison.',items:[['Watch with questions','Note the features and topics you want to understand before starting a video.'],['Read alongside it','Use a model page to keep the listed specifications close at hand.'],['Compare your options','Bring the tractors you are considering into one side-by-side view.']],link:['Read expert reviews','/reviews']},
};
export function PageSupport(){
  const path=usePathname();const first=path.split('/')[1];const key=({tractor:'tractors','new-tractors':'tractors','upcoming-tractors':'tractors',brand:'brands',category:'articles',news:'articles'} as Record<string,string>)[first]??first;const guide=guides[key];
  if(!guide)return null;
  const shortlistIcons=['/icons/tabler/book-2.svg','/icons/tabler/settings.svg','/icons/tabler/news.svg'];
  const isTractorCatalog=first==='tractors'||first==='new-tractors';
  return <section className={`page-support${isTractorCatalog?' page-support-shortlist':''}`} aria-labelledby="page-support-title"><LocalizedElement as="div" className="support-heading"><LocalizedElement as="p">{guide.eyebrow}</LocalizedElement><LocalizedElement as="h2" id="page-support-title">{guide.title}</LocalizedElement><LocalizedElement as="span">{guide.intro}</LocalizedElement></LocalizedElement><LocalizedElement as="div" className="support-grid">{guide.items.map(([title,text],index)=><article key={title}>{isTractorCatalog&&<LocalizedElement as="span" className="support-icon" aria-hidden="true"><LocalizedElement as="img" src={shortlistIcons[index]} alt="" width={32} height={32}/></LocalizedElement>}<LocalizedElement as="div" className="support-step-copy"><LocalizedElement as="span" className="support-number">0{index+1}</LocalizedElement><LocalizedElement as="h3">{title}</LocalizedElement><LocalizedElement as="p">{text}</LocalizedElement></LocalizedElement></article>)}</LocalizedElement><LocalizedElement as="a" className="text-action" href={guide.link[1]}>{guide.link[0]} <LocalizedElement as="span">→</LocalizedElement></LocalizedElement></section>;
}
