'use client';import {HeaderSearch} from './HeaderSearch';import {HomepageHeader} from './HomepageHeader';import '@/app/public-pages.css';import '@/app/reference-home.css';import {PublicBreadcrumbs,PageSupport} from './PublicPageParts';import {usePathname} from 'next/navigation';import{useState,type ReactNode}from'react';import{useAuth}from'@/hooks/useAuth';import{useSiteSettings}from'@/hooks/useSiteSettings';
const links=[['Home','/'],['Tractors','/tractors'],['Brands','/brands'],['Reviews','/reviews'],['Compare','/compare'],['Equipment','/equipment'],['Agriculture','/articles'],['Videos','/videos'],['Dealers','/dealers']];
export {useSiteSettings};
export function SiteHeader(){const path=usePathname();const[open,setOpen]=useState(false);const{user}=useAuth();const s=useSiteSettings();const name=s.websiteName||'RJ Tractor Techs';return <><div className="topbar"><p>{s.tagline||"India's independent tractor research & farming media platform"}</p><a href={s.youtube||'https://www.youtube.com/@Rjtractortechs'} target="_blank" rel="noreferrer">Watch on YouTube ↗</a></div><header className="site-header"><a className="brand" href="/"><span className="brand-mark">{s.logo?<img src={s.logo} alt=""/>:'RJ'}</span><span className="brand-copy"><strong>{name.replace('RJ ','')}</strong><small>Reviews · Specs · Farming</small></span></a><nav className="desktop-nav" aria-label="Main navigation">{links.map(([label,href])=><a key={href} href={href} className={path===href?'active':undefined} aria-current={path===href?'page':undefined}>{label}</a>)}</nav><div className="header-actions"><HeaderSearch onOpen={()=>setOpen(false)}/><a className="round-action desktop-only" href={user?'/account':'/login'} aria-label="Account">{user?'●':'♙'}</a><button aria-label="Menu" aria-expanded={open} onClick={()=>setOpen(!open)}>☰</button></div></header>{open&&<nav className="mobile-nav">{links.map(([label,href])=><a key={href} href={href}>{label}<span>→</span></a>)}<a href={user?'/account':'/login'}>{user?'My account':'Sign in'}<span>→</span></a></nav>}</>}
export function SiteFooter(){const s=useSiteSettings();const socialLinks=[
  {label:'YouTube',href:s.youtube||'https://www.youtube.com/@Rjtractortechs',icon:'/icons/tabler/brand-youtube.svg'},
  {label:'Instagram',href:s.instagram,icon:'https://cdn.jsdelivr.net/npm/@tabler/icons@latest/icons/outline/brand-instagram.svg'},
  {label:'Facebook',href:s.facebook,icon:'https://cdn.jsdelivr.net/npm/@tabler/icons@latest/icons/outline/brand-facebook.svg'},
].filter(item=>item.href);return <footer><div className="footer-main"><div className="footer-brand"><a className="brand" href="/"><span className="brand-mark">{s.logo?<img src={s.logo} alt=""/>:'RJ'}</span><span className="brand-copy"><strong>{(s.websiteName||'RJ Tractor Techs').replace('RJ ','')}</strong><small>Reviews · Specs · Farming</small></span></a><p>{s.footer||'Independent tractor information and practical farming knowledge, made easier to explore.'}</p>{s.email&&<a href={`mailto:${s.email}`}>{s.email}</a>}{s.phone&&<a href={`tel:${s.phone}`}>{s.phone}</a>}</div><div><h4>Research</h4>{links.slice(1,5).map(([l,h])=><a key={h} href={h}>{l}</a>)}</div><div><h4>Learn</h4>{links.slice(5).map(([l,h])=><a key={h} href={h}>{l}</a>)}</div><div><h4>Company</h4>{[['About','/about'],['Contact','/contact'],['Privacy','/privacy-policy'],['Terms','/terms-and-conditions'],['Disclaimer','/disclaimer']].map(([l,h])=><a key={h} href={h}>{l}</a>)}</div></div><div className="footer-bottom"><span>{s.copyright||`© ${new Date().getFullYear()} RJ Tractor Techs.`}</span><nav className="footer-socials" aria-label="Social media">{socialLinks.map(item=><a key={item.label} href={item.href} target="_blank" rel="noreferrer" aria-label={item.label} title={item.label}><img src={item.icon} alt="" width="18" height="18"/></a>)}</nav></div></footer>}
export function PublicShell({children}:{children:ReactNode}){return <div className="public-site"><div className="reference-home public-shared-header"><HomepageHeader/></div><PublicBreadcrumbs/>{children}<PageSupport/><div className="reference-home public-shared-footer"><div className="home-v2 home-footer"><SiteFooter/></div></div></div>}
