'use client';
import { LocalizedElement } from '@/components/LocalizedElement';
import {HeaderSearch} from './HeaderSearch';import {HomepageHeader} from './HomepageHeader';import '@/app/public-pages.css';import '@/app/reference-home.css';import '@/app/automotive-home.css';import {PageSupport} from './PublicPageParts';import {usePathname} from 'next/navigation';import{useState,type ReactNode}from'react';import{useSiteSettings}from'@/hooks/useSiteSettings';
const links=[['Home','/'],['Tractors','/tractors'],['Brands','/brands'],['Reviews','/reviews'],['Compare','/compare'],['Equipment','/equipment'],['Agriculture','/articles'],['Videos','/videos'],['Dealers','/dealers']];
export {useSiteSettings};
export function SiteHeader(){const path=usePathname();const[open,setOpen]=useState(false);const s=useSiteSettings();const name=s.websiteName||'RJ Tractor Techs';return <><LocalizedElement as="div" className="topbar"><LocalizedElement as="p">{s.tagline||"India's independent tractor research & farming media platform"}</LocalizedElement><LocalizedElement as="a" href={s.youtube||'https://www.youtube.com/@Rjtractortechs'} target="_blank" rel="noreferrer">Watch on YouTube ↗</LocalizedElement></LocalizedElement><header className="site-header"><LocalizedElement as="a" className="brand" href="/" aria-label={name}>{s.logo?<LocalizedElement as="span" className="brand-mark"><LocalizedElement as="img" src={s.logo} alt={name}/></LocalizedElement>:<><LocalizedElement as="span" className="brand-mark">RJ</LocalizedElement><LocalizedElement as="span" className="brand-copy"><LocalizedElement as="strong">{name.replace('RJ ','')}</LocalizedElement><LocalizedElement as="small">Reviews · Specs · Farming</LocalizedElement></LocalizedElement></>}</LocalizedElement><nav className="desktop-nav" aria-label="Main navigation">{links.map(([label,href])=><LocalizedElement as="a" key={href} href={href} className={path===href?'active':undefined} aria-current={path===href?'page':undefined}>{label}</LocalizedElement>)}</nav><LocalizedElement as="div" className="header-actions"><HeaderSearch onOpen={()=>setOpen(false)}/><LocalizedElement as="button" aria-label="Menu" aria-expanded={open} onClick={()=>setOpen(!open)}>☰</LocalizedElement></LocalizedElement></header>{open&&<nav className="mobile-nav">{links.map(([label,href])=><LocalizedElement as="a" key={href} href={href}>{label}<LocalizedElement as="span">→</LocalizedElement></LocalizedElement>)}</nav>}</>}
export { SiteFooter } from './SiteFooter';
import { SiteFooter } from './SiteFooter';
export function PublicShell({children}:{children:ReactNode}){return <LocalizedElement as="div" className="public-site"><LocalizedElement as="div" className="reference-home public-shared-header"><HomepageHeader/></LocalizedElement>{children}<PageSupport/><LocalizedElement as="div" className="reference-home public-shared-footer"><LocalizedElement as="div" className="rj-footer-shell"><SiteFooter/></LocalizedElement></LocalizedElement></LocalizedElement>}
