import { tractorAdminFields } from './tractor-specifications';
import { homepageSections } from './homepage-sections';
export type AdminField={key:string;label:string;type?:'text'|'textarea'|'number'|'boolean'|'image'|'select'|'lines';required?:boolean;options?:{value:string;label:string}[];source?:string};
export type AdminSection={label:string;collection:string;description:string;fields:AdminField[];readOnly?:boolean;allowCreate?:boolean;moderation?:boolean};

const common:AdminField[]=[{key:'title',label:'Title',required:true}];
export const adminSections:Record<string,AdminSection>={
  tractors:{label:'Tractors',collection:'tractors',description:'Model details, images and verified specifications. Add fields manually or upload a specification CSV; saved values appear on model and comparison pages.',fields:tractorAdminFields},
  brands:{label:'Brands',collection:'brands',description:'Manufacturer profiles and brand landing pages.',fields:[...common,{key:'logo',label:'Logo',type:'image'},{key:'description',label:'Description',type:'textarea'}]},
  equipment:{label:'Equipment',collection:'equipment',description:'Implements, tyres and accessories.',fields:[...common,{key:'category',label:'Category'},{key:'price',label:'Price',type:'number'},{key:'image',label:'Image',type:'image'},{key:'description',label:'Description',type:'textarea'}]},
  articles:{label:'Articles',collection:'articles',description:'Guides, news and buying advice.',fields:[...common,{key:'articleType',label:'Content type',type:'select',options:[{value:'article',label:'Article / guide'},{value:'news',label:'News'}]},{key:'categoryId',label:'Category',type:'select',source:'articleCategories'},{key:'image',label:'Cover image',type:'image'},{key:'excerpt',label:'Excerpt',type:'textarea'},{key:'content',label:'Article body',type:'textarea'}]},
  categories:{label:'Categories',collection:'articleCategories',description:'Editorial categories and topic landing pages.',fields:[...common,{key:'description',label:'Description',type:'textarea'}]},
  videos:{label:'Videos',collection:'videos',description:'Video library and embeds.',fields:[...common,{key:'youtubeId',label:'YouTube video URL or ID',required:true},{key:'thumbnail',label:'Thumbnail',type:'image'},{key:'description',label:'Description',type:'textarea'}]},
  dealers:{label:'Dealers',collection:'dealers',description:'Dealer directory and contact details.',fields:[...common,{key:'brand',label:'Brand'},{key:'district',label:'District'},{key:'city',label:'City'},{key:'state',label:'State'},{key:'phone',label:'Phone'},{key:'address',label:'Address',type:'textarea'}]},
  banners:{label:'Banners',collection:'banners',description:'Optional campaign cards below the hero. Hero slides are managed separately.',fields:[...common,{key:'image',label:'Image',type:'image'},{key:'ctaLabel',label:'CTA label'},{key:'ctaUrl',label:'CTA URL'}]},
  'hero-slides':{label:'Hero slides',collection:'heroSlides',description:'Upload images in display order. Saved changes appear automatically on the homepage.',fields:[{key:'title',label:'Slide name',required:true},{key:'order',label:'Display order (automatic if blank)',type:'number'},{key:'image',label:'Hero image',type:'image'},{key:'backgroundColor',label:'Blank slide colour'}]},
  partners:{label:'Partners',collection:'partners',description:'Partner logos shown in the scrolling carousel above the homepage footer.',fields:[{key:'title',label:'Partner name',required:true},{key:'order',label:'Display order (automatic if blank)',type:'number'},{key:'image',label:'Partner logo',type:'image'}]},
  advertisements:{label:'Advertisements',collection:'advertisements',description:'Sponsored images in the homepage promotions section.',fields:[...common,{key:'image',label:'Creative',type:'image'},{key:'destinationUrl',label:'Destination URL'}]},
  seo:{label:'SEO',collection:'seo',description:'Per-route search metadata.',fields:[{key:'title',label:'Page title',required:true},{key:'path',label:'Route path',required:true},{key:'description',label:'Meta description',type:'textarea'},{key:'image',label:'Social image',type:'image'}]},
  settings:{label:'Settings',collection:'settings',description:'Global contact and website configuration.',fields:[{key:'key',label:'Setting',type:'select',required:true,options:['websiteName','tagline','logo','youtube','instagram','facebook','footer','email','phone','copyright','about','privacy-policy','terms-and-conditions','disclaimer','cookie-policy'].map(value=>({value,label:value}))},{key:'value',label:'Value',type:'textarea'}]},
  homepage:{label:'Homepage',collection:'homepageSections',description:'Homepage section titles, visibility and order. The tractor showcase always follows the hero.',fields:[{key:'title',label:'Section title (optional)'},{key:'key',label:'Section',type:'select',required:true,options:homepageSections.map(item=>({value:item.key,label:item.title}))},{key:'order',label:'Display order',type:'number'},{key:'visible',label:'Visible',type:'boolean'}]},
  'contact-messages':{label:'Contact inbox',collection:'contactMessages',description:'Messages submitted through the public contact form.',allowCreate:false,fields:[{key:'name',label:'Name'},{key:'email',label:'Email'},{key:'phone',label:'Phone'},{key:'message',label:'Message',type:'textarea'}]},
  subscribers:{label:'Subscribers',collection:'newsletterSubscribers',description:'Archived subscriber records. The newsletter signup is no longer displayed.',allowCreate:false,fields:[{key:'email',label:'Email',required:true}]},
};
