import { tractorAdminFields } from './tractor-specifications';
import { homepageSections } from './homepage-sections';
export type AdminField={key:string;label:string;type?:'text'|'textarea'|'number'|'boolean'|'image'|'select'|'lines';required?:boolean;options?:{value:string;label:string}[];source?:string};
export type AdminSection={label:string;collection:string;description:string;fields:AdminField[];readOnly?:boolean;allowCreate?:boolean;moderation?:boolean};

const common:AdminField[]=[{key:'title',label:'Title',required:true}];
export const adminSections:Record<string,AdminSection>={
  'expert-reviews':{label:'Editorial reviews',collection:'expertReviews',description:'Write a draft, link a tractor, document your testing and publish when the review is ready.',fields:[...common,{key:'status',label:'Publication status',type:'select',options:[{value:'draft',label:'Draft'},{value:'published',label:'Published'},{value:'archived',label:'Archived'}]},{key:'tractorId',label:'Tractor',type:'select',source:'tractors'},{key:'authorName',label:'Author'},{key:'image',label:'Cover image',type:'image'},{key:'excerpt',label:'Summary',type:'textarea'},{key:'content',label:'Full review',type:'textarea'},{key:'score',label:'Overall score / 10',type:'number'},{key:'verdict',label:'Verdict',type:'textarea'},{key:'pros',label:'Strengths (one per line)',type:'lines'},{key:'cons',label:'Limitations (one per line)',type:'lines'},{key:'methodology',label:'How this tractor was assessed',type:'textarea'},{key:'disclosure',label:'Sponsorship or loan disclosure',type:'textarea'}]},
  tractors:{label:'Tractors',collection:'tractors',description:'Model details, images and verified specifications. Add fields manually or upload a specification CSV; saved values appear on model and comparison pages.',fields:tractorAdminFields},
  brands:{label:'Brands',collection:'brands',description:'Manage brands and their logos here. Published brand logos also appear in the homepage partner strip.',fields:[...common,{key:'logo',label:'Logo',type:'image'},{key:'order',label:'Homepage display order',type:'number'},{key:'description',label:'Description',type:'textarea'}]},
  equipment:{label:'Equipment',collection:'equipment',description:'Implements, tyres and accessories.',fields:[...common,{key:'category',label:'Category'},{key:'price',label:'Price',type:'number'},{key:'image',label:'Image',type:'image'},{key:'description',label:'Description',type:'textarea'}]},
  articles:{label:'Articles',collection:'articles',description:'Guides, news and buying advice.',fields:[...common,{key:'articleType',label:'Content type',type:'select',options:[{value:'article',label:'Article / guide'},{value:'news',label:'News'}]},{key:'categoryId',label:'Category',type:'select',source:'articleCategories'},{key:'image',label:'Cover image',type:'image'},{key:'excerpt',label:'Excerpt',type:'textarea'},{key:'content',label:'Article body',type:'textarea'}]},
  categories:{label:'Categories',collection:'articleCategories',description:'Editorial categories and topic landing pages.',fields:[...common,{key:'description',label:'Description',type:'textarea'}]},
  videos:{label:'Homepage videos',collection:'videos',description:'Control Recent videos on YouTube: edit the video link, thumbnail, homepage visibility and order. Publish to show it; draft or archive to hide it.',fields:[...common,{key:'showOnHomepage',label:'Show in homepage video slider',type:'boolean'},{key:'order',label:'Homepage display order (1 first)',type:'number'},{key:'youtubeId',label:'YouTube video URL or ID',required:true},{key:'thumbnail',label:'Thumbnail',type:'image'},{key:'description',label:'Description',type:'textarea'}]},
  dealers:{label:'Dealers',collection:'dealers',description:'Dealer directory, logo and contact details.',fields:[...common,{key:'logo',label:'Dealer logo / homepage image',type:'image'},{key:'order',label:'Homepage logo order',type:'number'},{key:'email',label:'Email'},{key:'whatsapp',label:'WhatsApp number'},{key:'pincode',label:'Postal code'},{key:'services',label:'Services (one per line)',type:'lines'},{key:'brand',label:'Brand'},{key:'district',label:'District'},{key:'city',label:'City'},{key:'state',label:'State'},{key:'phone',label:'Phone'},{key:'address',label:'Address',type:'textarea'}]},
  banners:{label:'Banners',collection:'banners',description:'Optional campaign cards below the hero. Hero slides are managed separately.',fields:[...common,{key:'image',label:'Image',type:'image'},{key:'ctaLabel',label:'CTA label'},{key:'ctaUrl',label:'CTA URL'}]},
  'hero-slides':{label:'Hero slides',collection:'heroSlides',description:'Upload images in display order. Saved changes appear automatically on the homepage.',fields:[{key:'title',label:'Slide name',required:true},{key:'order',label:'Display order (automatic if blank)',type:'number'},{key:'image',label:'Hero image',type:'image'},{key:'backgroundColor',label:'Blank slide colour'},{key:'heading',label:'Headline (blank uses homepage title)'},{key:'description',label:'Supporting text',type:'textarea'},{key:'imageAlt',label:'Image description for accessibility'},{key:'imageFit',label:'Image fit',type:'select',options:[{value:'cover',label:'Fill and crop'},{value:'contain',label:'Show complete image'}]},{key:'imagePosition',label:'Image focus',type:'select',options:[{value:'center',label:'Centre'},{value:'left',label:'Left'},{value:'right',label:'Right'},{value:'top',label:'Top'},{value:'bottom',label:'Bottom'}]},{key:'duration',label:'Seconds before next slide (3–30)',type:'number'},{key:'ctaLabel',label:'Primary button text'},{key:'ctaUrl',label:'Primary button link'},{key:'secondaryCtaLabel',label:'Secondary button text'},{key:'secondaryCtaUrl',label:'Secondary button link'}]},
  partners:{label:'Partners',collection:'partners',description:'Upload partner logos for the scrolling strip below the homepage hero. Saved logos appear automatically. Use Display order to arrange them.',fields:[{key:'title',label:'Partner name',required:true},{key:'order',label:'Display order (automatic if blank)',type:'number'},{key:'image',label:'Partner logo',type:'image',required:true}]},
  advertisements:{label:'Advertisements',collection:'advertisements',description:'Sponsored images in the homepage promotions section.',fields:[...common,{key:'image',label:'Creative',type:'image'},{key:'destinationUrl',label:'Destination URL'}]},
  seo:{label:'SEO',collection:'seo',description:'Per-route search metadata.',fields:[{key:'title',label:'Page title',required:true},{key:'path',label:'Route path',required:true},{key:'description',label:'Meta description',type:'textarea'},{key:'image',label:'Social image',type:'image'}]},
  settings:{label:'Settings',collection:'settings',description:'Global contact and website configuration.',fields:[{key:'key',label:'Setting',type:'select',required:true,options:['websiteName','tagline','logo','youtube','instagram','facebook','footer','email','phone','copyright','about','privacy-policy','terms-and-conditions','disclaimer','cookie-policy','videoSource'].map(value=>({value,label:value}))},{key:'value',label:'Value',type:'textarea'}]},
  homepage:{label:'Homepage',collection:'homepageSections',description:'Homepage section titles, visibility and order. Display order controls the public homepage, including the hero and tractor showcase.',fields:[{key:'title',label:'Section title (optional)'},{key:'key',label:'Section',type:'select',required:true,options:homepageSections.map(item=>({value:item.key,label:item.title}))},{key:'order',label:'Display order',type:'number'},{key:'visible',label:'Visible',type:'boolean'}]},
  'contact-messages':{label:'Contact inbox',collection:'contactMessages',description:'Messages submitted through the public contact form.',allowCreate:false,fields:[{key:'name',label:'Name'},{key:'email',label:'Email'},{key:'phone',label:'Phone'},{key:'message',label:'Message',type:'textarea'}]},
  subscribers:{label:'Subscribers',collection:'newsletterSubscribers',description:'Archived subscriber records. The newsletter signup is no longer displayed.',allowCreate:false,fields:[{key:'email',label:'Email',required:true}]},
};

// Every public content module exposes publication state without forcing edits live.
for (const section of Object.values(adminSections)) {
  if (['contactMessages','newsletterSubscribers','expertReviews'].includes(section.collection)) continue;
  section.fields.push({key:'status',label:'Publication status',type:'select',options:[
    {value:'draft',label:'Draft — hidden from website'},
    {value:'published',label:'Published — visible on website'},
    {value:'archived',label:'Archived — hidden from website'},
  ]});
}

// Telugu copy is optional; public pages retain English when it is not supplied.
const bilingualKeys = new Set(['title','heading','imageAlt','secondaryCtaLabel','description','excerpt','content','verdict','methodology','disclosure','ctaLabel','pros','cons']);
for (const section of Object.values(adminSections)) {
  if (!['tractors','brands','articles','articleCategories','videos','equipment','dealers','expertReviews','banners','heroSlides','partners','homepageSections'].includes(section.collection)) continue;
  section.fields = section.fields.flatMap(field => bilingualKeys.has(field.key) ? [field, { key: field.key + 'Te', label: field.label + ' — Telugu (optional)', type: ['textarea','lines'].includes(field.type ?? '') ? 'textarea' as const : 'text' as const }] : [field]);
}
