export type AdminField={key:string;label:string;type?:'text'|'textarea'|'number'|'boolean'|'status'|'image';required?:boolean};
export type AdminSection={label:string;collection:string;description:string;fields:AdminField[]};

const common:AdminField[]=[{key:'title',label:'Title',required:true},{key:'slug',label:'Slug',required:true},{key:'status',label:'Status',type:'status'}];
export const adminSections:Record<string,AdminSection>={
  tractors:{label:'Tractors',collection:'tractors',description:'Models, specifications, pricing and media.',fields:[{key:'brand',label:'Brand',required:true},{key:'model',label:'Model',required:true},{key:'slug',label:'Slug',required:true},{key:'horsepower',label:'Horsepower',type:'number'},{key:'price',label:'Starting price',type:'number'},{key:'image',label:'Hero image',type:'image'},{key:'description',label:'Description',type:'textarea'},{key:'status',label:'Status',type:'status'}]},
  brands:{label:'Brands',collection:'brands',description:'Manufacturer profiles and brand landing pages.',fields:[...common,{key:'logo',label:'Logo',type:'image'},{key:'description',label:'Description',type:'textarea'}]},
  reviews:{label:'Owner reviews',collection:'reviews',description:'Moderate community ratings and reports.',fields:[{key:'tractorName',label:'Tractor',required:true},{key:'userName',label:'Reviewer'},{key:'rating',label:'Rating',type:'number'},{key:'comment',label:'Review',type:'textarea'},{key:'status',label:'Status',type:'status'}]},
  'expert-reviews':{label:'Expert reviews',collection:'expertReviews',description:'Editorial tests and verdicts.',fields:[...common,{key:'image',label:'Cover image',type:'image'},{key:'excerpt',label:'Excerpt',type:'textarea'},{key:'score',label:'Score',type:'number'}]},
  equipment:{label:'Equipment',collection:'equipment',description:'Implements, tyres and accessories.',fields:[...common,{key:'category',label:'Category'},{key:'price',label:'Price',type:'number'},{key:'image',label:'Image',type:'image'},{key:'description',label:'Description',type:'textarea'}]},
  articles:{label:'Articles',collection:'articles',description:'Guides, news and buying advice.',fields:[...common,{key:'category',label:'Category'},{key:'image',label:'Cover image',type:'image'},{key:'excerpt',label:'Excerpt',type:'textarea'},{key:'content',label:'Article body',type:'textarea'}]},
  videos:{label:'Videos',collection:'videos',description:'Video library and embeds.',fields:[...common,{key:'youtubeId',label:'YouTube video ID'},{key:'thumbnail',label:'Thumbnail',type:'image'},{key:'description',label:'Description',type:'textarea'}]},
  dealers:{label:'Dealers',collection:'dealers',description:'Dealer directory and contact details.',fields:[...common,{key:'city',label:'City'},{key:'state',label:'State'},{key:'phone',label:'Phone'},{key:'address',label:'Address',type:'textarea'}]},
  banners:{label:'Banners',collection:'banners',description:'Homepage campaigns and promotional hero cards.',fields:[...common,{key:'image',label:'Image',type:'image'},{key:'ctaLabel',label:'CTA label'},{key:'ctaUrl',label:'CTA URL'}]},
  advertisements:{label:'Advertisements',collection:'advertisements',description:'Sponsored placements and schedules.',fields:[...common,{key:'placement',label:'Placement'},{key:'image',label:'Creative',type:'image'},{key:'destinationUrl',label:'Destination URL'}]},
  seo:{label:'SEO',collection:'seo',description:'Per-route search metadata.',fields:[{key:'title',label:'Page title',required:true},{key:'path',label:'Route path',required:true},{key:'description',label:'Meta description',type:'textarea'},{key:'image',label:'Social image',type:'image'},{key:'status',label:'Status',type:'status'}]},
  settings:{label:'Settings',collection:'settings',description:'Global contact and website configuration.',fields:[{key:'title',label:'Setting name',required:true},{key:'key',label:'Key',required:true},{key:'value',label:'Value',type:'textarea'},{key:'status',label:'Status',type:'status'}]},
};
