'use client';

import { useMemo,useState } from 'react';
import { PublicShell } from '@/components/SiteChrome';
import { LeadForm } from '@/components/LeadForm';
import { trackEvent } from '@/services/analytics';

function money(value:number){return new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number.isFinite(value)?value:0);}
export default function EmiCalculatorPage(){const [price,setPrice]=useState(800000);const [down,setDown]=useState(160000);const [rate,setRate]=useState(10.5);const [years,setYears]=useState(5);const [tracked,setTracked]=useState(false);const result=useMemo(()=>{const principal=Math.max(price-down,0);const months=Math.max(years*12,1);const monthlyRate=rate/1200;const emi=monthlyRate===0?principal/months:principal*monthlyRate*Math.pow(1+monthlyRate,months)/(Math.pow(1+monthlyRate,months)-1);const total=emi*months;return{principal,emi,total,interest:total-principal};},[price,down,rate,years]);function record(){if(!tracked){setTracked(true);trackEvent('emi_calculation',{tractor_price:price,loan_amount:result.principal,tenure_years:years});}}return <PublicShell><main className="emi-page"><section className="page-hero"><p>FINANCE PLANNING</p><h1>Tractor EMI calculator</h1><span>Estimate monthly loan payments, total interest and total payable before speaking with a lender.</span></section><section className="emi-workspace"><div className="emi-inputs"><h2>Loan details</h2><label>Tractor price <strong>{money(price)}</strong><input type="range" min="200000" max="3000000" step="10000" value={price} onChange={event=>{setPrice(Number(event.target.value));record();}}/><input type="number" min="0" value={price} onChange={event=>setPrice(Number(event.target.value))}/></label><label>Down payment <strong>{money(down)}</strong><input type="range" min="0" max={price} step="10000" value={Math.min(down,price)} onChange={event=>setDown(Number(event.target.value))}/><input type="number" min="0" max={price} value={down} onChange={event=>setDown(Number(event.target.value))}/></label><label>Interest rate <strong>{rate}%</strong><input type="range" min="0" max="20" step=".1" value={rate} onChange={event=>setRate(Number(event.target.value))}/></label><label>Loan tenure <strong>{years} years</strong><input type="range" min="1" max="10" step="1" value={years} onChange={event=>setYears(Number(event.target.value))}/></label></div><div className="emi-results"><p>ESTIMATED MONTHLY EMI</p><h2>{money(result.emi)}</h2><div><span>Loan amount<strong>{money(result.principal)}</strong></span><span>Total interest<strong>{money(result.interest)}</strong></span><span>Total payable<strong>{money(result.total)}</strong></span></div><small>This is an indicative calculation, not a finance offer. Actual terms depend on the lender and applicant.</small></div></section><section className="emi-enquiry"><LeadForm source="emi_calculator"/></section></main></PublicShell>;}

