'use client';

import { useEffect,useState } from 'react';
import { PublicShell } from '@/components/SiteChrome';
import { SetupNotice } from '@/components/SetupNotice';
import { isFirebaseConfigured } from '@/lib/firebase/client';
import { listDealers,type Dealer } from '@/services/media';

export default function DealersPage(){const [items,setItems]=useState<Dealer[]>([]);const [filters,setFilters]=useState({brand:'',state:'',district:'',city:''});const [loading,setLoading]=useState(isFirebaseConfigured);useEffect(()=>{if(!isFirebaseConfigured)return;setLoading(true);listDealers({brand:filters.brand||undefined,state:filters.state||undefined,district:filters.district||undefined,city:filters.city||undefined}).then(setItems).finally(()=>setLoading(false));},[filters]);return <PublicShell><main className="dealers-index"><section className="page-hero"><p>DEALER DIRECTORY</p><h1>Find tractor dealers</h1><span>Search published dealer profiles by brand and location.</span></section>{!isFirebaseConfigured?<SetupNotice/>:<section className="dealer-list"><div className="dealer-filters">{(['brand','state','district','city'] as const).map(field=><label key={field}>{field}<input value={filters[field]} onChange={event=>setFilters(current=>({...current,[field]:event.target.value}))} placeholder={'Enter '+field}/></label>)}<button onClick={()=>setFilters({brand:'',state:'',district:'',city:''})}>Clear filters</button></div>{loading?<div className="detail-loading">Loading dealers…</div>:!items.length?<div className="empty-state"><h3>No dealers found matching your filters.</h3><button onClick={()=>setFilters({brand:'',state:'',district:'',city:''})}>Clear filters</button></div>:<div className="dealer-grid">{items.map(item=><article key={item.id}><div className="dealer-logo">{item.logo?<img src={item.logo} alt={item.name+' logo'}/>:item.name.slice(0,2).toUpperCase()}</div><section><p>{item.verified?'✓ VERIFIED DEALER':'DEALER'}</p><h2>{item.name}</h2><span>{item.address}, {item.city}, {item.state}</span><small>{item.brand??'Multiple brands'}</small><a href={'/dealers/'+item.slug}>View dealer →</a></section></article>)}</div>}</section>}</main></PublicShell>;}

